#######################################################
# Dockerfile for the Beaglebone blue cross compilation
#######################################################

FROM debian:bullseye

RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y -q \
    gcc-arm-linux-gnueabihf \
    g++-arm-linux-gnueabihf \
    cmake
    
ENV AS=/usr/bin/arm-linux-gnueabihf-as \
    AR=/usr/bin/arm-linux-gnueabihf-ar \
    CC=/usr/bin/arm-linux-gnueabihf-gcc \
    CPP=/usr/bin/arm-linux-gnueabihf-cpp \
    CXX=/usr/bin/arm-linux-gnueabihf-g++ \
    LD=/usr/bin/arm-linux-gnueabihf-ld

    RUN echo "alias ll='ls -alF --color=auto'" >> /etc/bash.bashrc

WORKDIR /workspace
